export const FETCH_TV = 'FETCH_TV'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'

export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'
export const SUCCESS_REMOVE_FROM_FAVORITES = 'SUCCESS_REMOVE_FROM_FAVORITES'
export const FAILURE_REMOVE_FROM_FAVORITES = 'FAILURE_REMOVE_FROM_FAVORITES'

export const FETCH_DETAILS = 'FETCH_DETAILS'
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS'
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const SUCCESS_ADD_TO_FAVORITES = 'SUCCESS_ADD_TO_FAVORITES'
export const FAILURE_ADD_TO_FAVORITES = 'FAILURE_ADD_TO_FAVORITES'



